package org.example.Server.JDBC;

import org.example.Server.IFaces.UserManager;
import org.example.Server.POJOS.Administrator;
import org.example.Server.POJOS.Doctor;
import org.example.Server.POJOS.Patient;
import org.example.Server.POJOS.User;
import org.example.Server.JDBC.JDBCDoctorManager;

import javax.management.Query;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.*;


public class JDBCUserManager implements UserManager {

    private JDBCManager manager;

    public JDBCUserManager(JDBCManager manager){
        this.manager=manager;
    }

    @Override
    public void addUser(User user) {
        String sql = "INSERT INTO Users (email, password, role) VALUES (?, ?, ?)";

        try{
            PreparedStatement ps = manager.getConnection().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            //the return generated keys returns the ID autogenerated by increment

            ps.setString(1, user.getEmail());
            ps.setString(2, user.getPassword());
            ps.setString(3, user.getRole().name());

            ps.executeUpdate();

            ResultSet rs = ps.getGeneratedKeys();
            if(rs.next()){
                int user_id = rs.getInt(1);
                user.setUser_id(user_id);
            }
            ps.close();

        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    @Override
    public void deleteUserByEmail(String email){
        String sql = "DELETE FROM Users WHERE email = ?";
        try{
            PreparedStatement ps = manager.getConnection().prepareStatement(sql);
            ps.setString(1, email);

            ps.executeUpdate();
            ps.close();
        }catch (SQLException e){
            e.printStackTrace();
        }
    }
    @Override
    public void deleteUserById(int user_id){
        String sql = "DELETE FROM Users WHERE user_id = ?";
        try{
            PreparedStatement ps = manager.getConnection().prepareStatement(sql);
            ps.setInt(1, user_id);

            ps.executeUpdate();
            ps.close();
        }catch (SQLException e){
            e.printStackTrace();
        }
    }

    @Override
    //método temporal (luego lo pondremos encrypted password
    public void changePassword(int user_id, String new_password) {
        String sql = "UPDATE Users SET password = ? WHERE user_id = ?";
        try (PreparedStatement ps = manager.getConnection().prepareStatement(sql)) {
            ps.setString(1, new_password);
            ps.setInt(2,user_id);

            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    //Para cuando creemos los menús, ponemos este método, no va aquí
   /* private void login() throws Exception {
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));

        System.out.println("Email: \n");
        String email = reader.readLine();

        System.out.println("Password: \n");
        String password = reader.readLine();

        User u = new User() {};
        checkPassword(email, password);

        if (u != null & u.getRole().equals("ADMINISTRATOR")) {
            System.out.println("Login of administrator successful!");
            //le pasamos el admin menu cuando lo creemos
            //adminMenu
        } else if (u != null & u.getRole().equals("DOCTOR")) {
            System.out.println("Login of doctor successful!");
            //le pasamos el doctor menu cuando lo creemos
            //doctorMenu

        } else if (u != null & u.getRole().equals("PATIENT")) {
            System.out.println("Login of patient successful!");
            //le pasamos el patient menu cuando lo creemos
            //patientMenu
        }

    }*/
    @Override
    public boolean checkPassword(String username, String password) {
        String sql = "SELECT password FROM users WHERE email = ?";
        try{
            PreparedStatement stmt = manager.getConnection().prepareStatement(sql);
            stmt.setString(1, username);

            ResultSet rs = stmt.executeQuery();

            if(rs.next()){
                String pass = rs.getString("password");
                if(pass.equals(password)){
                    return true;
                }
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        return false;
    }

    //Tambien podriamos hacer el changeEMail pasandolo un objeto User
    @Override
    public void changeEmail(int user_id, String new_email) {
        String sql = "UPDATE Users SET email = ? WHERE user_id = ?";
        try (PreparedStatement ps = manager.getConnection().prepareStatement(sql)) {
            ps.setString(1, new_email);
            ps.setInt(2, user_id);
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    @Override
    public User getUserByEmail(String email) {
        User user = null;
        String sql = "SELECT * FROM Users WHERE email = ?";

        try (PreparedStatement ps = manager.getConnection().prepareStatement(sql)) {
            ps.setString(1, email);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                int user_id = rs.getInt("user_id");
                String password = rs.getString("password");
                User.Role role = User.Role.valueOf(rs.getString("role"));

                switch (role){
                    case ADMINISTRATOR: {
                        String sql2 = "SELECT name, surname, phone FROM Administrators WHERE admin_id = ?";
                        PreparedStatement ps2 = manager.getConnection().prepareStatement(sql2);
                        ps2.setInt(1, user_id);

                        ResultSet  rs2 = ps2.executeQuery();
                        if(rs2.next()){

                            String name = rs2.getString("name");
                            String surname = rs2.getString("surname");
                            int phone = rs2.getInt("phone");
                            user = new Administrator(user_id, email, password, name, surname, phone);

                        }
                        rs2.close();
                        ps2.close();
                        break;
                    }
                    case DOCTOR:{
                        String sql3 = "SELECT name, surname, phone FROM Doctors WHERE doctor_id = ?";
                        PreparedStatement ps3 = manager.getConnection().prepareStatement(sql3);
                        ps3.setInt(1, user_id);

                        ResultSet  rs3 = ps3.executeQuery();
                        if(rs3.next()){

                            String name = rs3.getString("name");
                            String surname = rs3.getString("surname");
                            int phone = rs3.getInt("phone");
                            user = new Doctor(user_id, email, password, name, surname, phone);

                        }
                        rs3.close();
                        ps3.close();


                        break;
                    } case PATIENT:{
                        String sql4 = "SELECT name, surname, dob, phone, medicalHistory, sex, doctor_id FROM Patients WHERE patient_id = ?"; //FATLARIA METER LOS RECORDINGS
                        PreparedStatement ps4 = manager.getConnection().prepareStatement(sql4);
                        ps4.setInt(1, user_id);

                        ResultSet  rs4 = ps4.executeQuery();
                        if(rs4.next()){

                            String name = rs4.getString("name");
                            String surname = rs4.getString("surname");
                            int phone = rs4.getInt("phone");
                            Date dob = rs4.getDate("dob");
                            String medicalHistory = rs4.getString("medicalHistory");
                            Patient.Sex sex = Patient.Sex.valueOf(rs.getString("sex"));
                            int doctor_id = rs4.getInt("doctor_id");

                            user = new Patient(user_id, password, name, surname, dob, phone, medicalHistory, sex, doctor_id); //FATLARIA METER LOS RECORDINGS y el MAIL EN CONSTRUCTOR

                        }
                        rs4.close();
                        ps4.close();
                        break;
                    }
                    default: {
                        throw new IllegalArgumentException("Role not recognized");
                    }
                }

            }
            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return user;
    }

}
